[package]
name = "q_spsc"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "q_spsc"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
libc = "0.2"

[dev-dependencies]
criterion = "0.5"
crossbeam = "0.8"

[[bench]]
name = "spsc_bench"
harness = false


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1

