[package]
name = "parquet_ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive"] }
sysinfo = { version = "0.34.0", default-features = false, features = ["system"] }
parquet = "55.0.0"
arrow = { version = "55.0.0", features = ["ipc", "test_utils", "prettyprint", "json","ffi"] }
libc = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lib]
name = "parquet_ffi"
crate-type = ["staticlib", "cdylib", "rlib"]

